### ISSUE TITLE
Engineering Notations

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/framesoc#87]
What do you think about that https://github.com/soctrace-inria/ocelotl/issues/88 for Framesoc?
Very useful for working with time units since 10's exposant matches with ns, us, ms, s...

**Comment by generoso** [comment]
Finally I implemented a solution where the most convenient time unit is actually displayed,
trying to limiting the decimal digits if possible. This format is extremely practical and easy for the user.

E.g. If the timestamp is 123123123 ns, "123.12 ms" is displayed.
The number of decimal digits (2 in the example) changes according to the context (in order to be able to distinguish two different numbers).

@dosimont  It could be interesting to try this with Ocelotl timebar as well. 
@ycorre Have a look at the TimestampFormat object in model plugin.

![screenshot from 2015-02-02 16 49 35](https://cloud.githubusercontent.com/assets/4248665/6003382/8abf50ce-aafb-11e4-9c22-3d4ded23ff2c.png)
